### ISSUE TITLE
Support GeoParquet for input for `convert` templates

### ISSUE THREAD

**Issue by cholmes** [fiboa/cli#32]
I was trying to use https://data.source.coop/cholmes/eurocrops/geoparquet-projected/FR_2018_EC21.parquet as input for a france eurocrops converter (see #31), but parquet wasn't recognized. This makes sense as read_file() depends on fiona, and fiona isn't built by default with parquet. Generally the [read_parquet](https://geopandas.org/en/stable/docs/reference/api/geopandas.read_parquet.html) method works better anyways (columnar instead of row based, faster, etc). 

I made a go at checking for .parquet in the filename and using it, but got some weird error. But if that sounds like a reasonable approach I can keep trying it.

**Comment by m-mohr** [comment]
I can give it a quick try next week, or you can send me the error message and we try to take it from there?

**Comment by cholmes** [comment]
The error message was something about the array size, I suspect it was just the one file I was working with - I first wanted to get the france eurocrops one working, so I didn't pursue it more yet. I can probably make the PR if you think the approach is good, and I'll just try with some other files.

**Comment by cholmes** [comment]
Tested with 3 other files, all worked well. And performance was much better for France than using the other formats.
