### ISSUE TITLE
Add an option in `convert` to utilize a local version of the file instead of downloading?

### ISSUE THREAD

**Issue by cholmes** [fiboa/cli#33]
For larger datasets to convert it can be annoying to wait for it to download it from the source, and if you've already downloaded the data you could just use it locally. I was able to dig through the code and figure out that I could just change the URI in the code to point to a local file. But it'd be nice if I didn't have to change code, if I could just use the CLI and say something like -i / --in as an optional argument to point at a file locally. It'd have to be the exact same as the one that gets downloaded online.

Open to other ways to achieve this, just seems like it'd be nice in places with slow connections, etc.

**Comment by m-mohr** [comment]
You can use the `-c` Option for this.

**Comment by cholmes** [comment]
Ah cool! Sorry I missed it. The new explanation looks much better.
