### ISSUE TITLE
List out the available conversions in `convert` CLI

### ISSUE THREAD

**Issue by cholmes** [fiboa/cli#34]
It'd be great if there was some way to know what the available 'DATASET' strings are for `fiboa convert`, like list their exact names and maybe a little info about them. Right now I think I have to look at the code to get the names?

Could be a separate command, like `fiboa convert list-datasets` or could perhaps just include them in `fiboa convert --help`

**Comment by m-mohr** [comment]
Good idea

**Comment by m-mohr** [comment]
As a first improvement:

![grafik](https://github.com/fiboa/cli/assets/8262166/36885a1e-15f7-41bc-8047-8bd1fdabab97)

**Comment by m-mohr** [comment]
And `fiboa converters`:

![grafik](https://github.com/fiboa/cli/assets/8262166/015ab240-f267-4b92-bcc0-2299b6854f11)

**Comment by cholmes** [comment]
Looks great!
