### ISSUE TITLE
If using `--cache` option in convert let user know the local file is getting used

### ISSUE THREAD

**Issue by cholmes** [fiboa/cli#39]
The update for a better message with `--cache` in https://github.com/fiboa/cli/commit/0e691afa43e7ed527d87540e010a1e79ecb63904 is great. But I still get a bit confused when using it, as the message is `Loading file from: https://zenodo.org/records/8229128/files/FR_2018.zip` even if it's using the local file.

Looking at the memory usage and timing it looks like it isn't downloading, but if I supply the wrong cache location it looks like it'll just download and use it there the next time. So it'd be nice to just inform the user that the file they supplied for the cache is actually getting used, like 'Using local file at </local/location> as a cache for https://zenodo.org/records/8229128/files/FR_2018.zip'

**Comment by m-mohr** [comment]
I can't determine where the actual file is loaded from because it's in a code path that shouldn't print to CLI.

I've changed to "Loading file". That is not telling where it's loading from, but at least it doesn't claim it's loading from HTTP when it is not. Generally improved the messages a bit.
